services:
  - type: web
    name: mixpostapp
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:zB/s3NLJYZTLd3Mep4ARe80iVm85aLTOiwSBoYYeYFQ=

      - key: APP_URL
        value: https://mixpostapp.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgres
          name: mixpost-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromService:
          type: postgres
          name: mixpost-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgres
          name: mixpost-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: mixpost-db
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: mixpost-redis
          property: host
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: mixpost-redis
          property: password
      - key: QUEUE_CONNECTION
        value: redis

  - type: worker
    name: mixpost-worker
    env: docker
    dockerfilePath: ./Dockerfile
    startCommand: "php artisan queue:work"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:zB/s3NLJYZTLd3Mep4ARe80iVm85aLTOiwSBoYYeYFQ=
        
      - key: APP_URL
        value: https://mixpostapp.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: postgres
          name: mixpost-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromService:
          type: postgres
          name: mixpost-db
          property: database
      - key: DB_USERNAME
        fromService:
          type: postgres
          name: mixpost-db
          property: user
      - key: DB_PASSWORD
        fromService:
          type: postgres
          name: mixpost-db
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: mixpost-redis
          property: host
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: mixpost-redis
          property: password
      - key: QUEUE_CONNECTION
        value: redis

  - type: postgres
    name: mixpost-db
    plan: free

  - type: redis
    name: mixpost-redis
    plan: free
    
